"""Bilingual smoke test for the chat endpoint.

Runs a fixed set of 6 SAMA/CMA queries (3 EN + 3 AR) against /api/chat/query
and writes a markdown artifact comparing what each provider returned.

Usage:
    python tests/ab_smoke.py [--out artifacts/smoke_<provider>.md] [--url http://127.0.0.1:8765]

Designed to be run once against each LLM provider so the outputs can be
diffed by hand. Provider is read from the /health endpoint and stamped
into the output filename and frontmatter, so two runs against different
providers won't overwrite each other.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import httpx

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")


QUERIES: list[tuple[str, str, str]] = [
    ("EN-SAMA-1", "en", "What is the minimum capital requirement for a finance company?"),
    ("EN-CMA-1",  "en", "What is a qualified investor under CMA regulations?"),
    ("EN-CMA-2",  "en", "Are sukuk subject to disclosure requirements?"),
    ("AR-SAMA-1", "ar", "ما هي متطلبات رأس المال لشركة التمويل؟"),
    ("AR-CMA-1",  "ar", "ما تعريف المستثمر المؤهل في أنظمة هيئة السوق المالية؟"),
    ("AR-CMA-2",  "ar", "هل الصكوك تخضع لمتطلبات الإفصاح؟"),
]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", default="http://127.0.0.1:8765")
    parser.add_argument("--out", default=None)
    parser.add_argument("--timeout", type=float, default=240.0)
    args = parser.parse_args()

    with httpx.Client(timeout=args.timeout) as client:
        health = client.get(f"{args.url}/health").json()
        provider = health["llm_provider"]
        model = health["llm_model"]
        print(f"Server reports provider={provider!r} model={model!r}", flush=True)
        confirm = input("Continue? [y/N] ").strip().lower()
        if confirm != "y":
            print("Aborted.")
            return 1

        out_path = Path(args.out) if args.out else Path(f"artifacts/smoke_{provider}.md")
        out_path.parent.mkdir(parents=True, exist_ok=True)

        results: list[dict] = []
        for qid, lang, question in QUERIES:
            print(f"[{qid}] {question[:60]}...", flush=True)
            t0 = time.monotonic()
            try:
                r = client.post(f"{args.url}/api/chat/query", json={"question": question})
                r.raise_for_status()
                data = r.json()
                elapsed = time.monotonic() - t0
                print(f"  -> regulator={data['regulator']}  sources={len(data['sources'])}  ({elapsed:.1f}s)")
                results.append({
                    "id": qid, "lang": lang, "question": question,
                    "elapsed_s": round(elapsed, 1), **data,
                })
            except Exception as e:
                elapsed = time.monotonic() - t0
                print(f"  -> ERROR: {e}  ({elapsed:.1f}s)")
                results.append({
                    "id": qid, "lang": lang, "question": question,
                    "elapsed_s": round(elapsed, 1), "error": str(e),
                })

    lines: list[str] = [
        f"# Chat-endpoint smoke run — provider: `{provider}` (model `{model}`)",
        "",
        f"Backend: `{args.url}`  ·  Queries: {len(QUERIES)}  ·  Generated by `tests/ab_smoke.py`.",
        "",
        "Re-run the same script against the other provider (edit `.env`, restart server)",
        "to produce a parallel artifact for side-by-side comparison.",
        "",
    ]
    for r in results:
        lines += [
            f"## {r['id']}  ({r['lang']}, {r['elapsed_s']}s)",
            "",
            "**Question**",
            "",
            f"> {r['question']}",
            "",
        ]
        if "error" in r:
            lines += ["**ERROR**", "", f"```\n{r['error']}\n```", ""]
            continue
        lines += [
            f"**Regulator:** `{r['regulator']}`",
            "",
            "**Sources**",
            "",
        ]
        if not r["sources"]:
            lines.append("_(none)_")
        else:
            for s in r["sources"]:
                title = f": {s['title']}" if s.get("title") else ""
                lines.append(f"- {s['document']} — {s['article']}{title}")
        lines += ["", "**Answer**", "", r["answer"], "", "---", ""]

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {out_path} ({out_path.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
