"""Export helpers for chat, brief, and library conversations.

This module ships only the Markdown variants of each export. DOCX and PDF
variants live in app/core/exports_docx.py and app/core/exports_pdf.py
(separate so the Arabic-shaping + ReportLab dependencies only load on demand).
"""

from __future__ import annotations

import logging
from datetime import datetime

try:
    from hijridate import Gregorian as _HijriGregorian
    _HAS_HIJRIDATE = True
except ImportError:
    _HAS_HIJRIDATE = False

logger = logging.getLogger(__name__)

_HIJRI_AR_MONTHS = {
    1: "محرم", 2: "صفر", 3: "ربيع الأول", 4: "ربيع الآخر",
    5: "جمادى الأولى", 6: "جمادى الآخرة", 7: "رجب", 8: "شعبان",
    9: "رمضان", 10: "شوال", 11: "ذو القعدة", 12: "ذو الحجة",
}
_GREG_AR_MONTHS = {
    1: "يناير", 2: "فبراير", 3: "مارس", 4: "أبريل",
    5: "مايو", 6: "يونيو", 7: "يوليو", 8: "أغسطس",
    9: "سبتمبر", 10: "أكتوبر", 11: "نوفمبر", 12: "ديسمبر",
}
_AR_DIGIT_TRANSLATE = str.maketrans("0123456789", "٠١٢٣٤٥٦٧٨٩")


def to_ar_digits(s: str) -> str:
    return s.translate(_AR_DIGIT_TRANSLATE)


def format_dual_date(
    dt: datetime | None = None,
    lang: str = "en",
    mode: str = "dual",
    with_time: bool = False,
) -> str:
    """Render a date in Gregorian / Hijri / dual format per user preference.

    Uses the official Umm al-Qura Hijri calendar (the calendar Saudi Arabia
    uses for all government, banking, and regulatory dates). Degrades to
    Gregorian-only if hijridate is unavailable.
    """
    if dt is None:
        dt = datetime.now()
    is_ar = lang == "ar"

    if is_ar:
        greg = to_ar_digits(f"{dt.day} {_GREG_AR_MONTHS[dt.month]} {dt.year}")
    else:
        greg = dt.strftime("%B %d, %Y")

    if mode == "gregorian":
        if with_time:
            t = dt.strftime("%H:%M")
            return f"{greg} — {to_ar_digits(t)}" if is_ar else f"{greg} at {t}"
        return greg

    hijri: str | None = None
    if _HAS_HIJRIDATE:
        try:
            h = _HijriGregorian(dt.year, dt.month, dt.day).to_hijri()
            if is_ar:
                hijri = to_ar_digits(f"{h.day} {_HIJRI_AR_MONTHS[h.month]} {h.year}")
            else:
                hijri = f"{h.day} {h.month_name()} {h.year}"
        except Exception as e:
            logger.warning("Hijri conversion failed for %s: %s", dt, e)

    if hijri is None:
        if with_time:
            t = dt.strftime("%H:%M")
            return f"{greg} — {to_ar_digits(t)}" if is_ar else f"{greg} at {t}"
        return greg

    if mode == "hijri":
        suffix = " هـ" if is_ar else " AH"
        out = hijri + suffix
        if with_time:
            t = dt.strftime("%H:%M")
            return f"{out} — {to_ar_digits(t)}" if is_ar else f"{out} at {t}"
        return out

    # dual
    if is_ar:
        out = f"{greg} م الموافق {hijri} هـ"
        if with_time:
            out = f"{out} — {to_ar_digits(dt.strftime('%H:%M'))}"
    else:
        out = f"{greg} ({hijri} AH)"
        if with_time:
            out = f"{out} at {dt.strftime('%H:%M')}"
    return out


def export_chat_markdown(messages: list[dict], date_format: str = "dual") -> str:
    """Render a chat conversation as Markdown."""
    if not messages:
        return "# TadqeeqAI Chat Export\n\n_(empty chat)_\n"
    lines = [
        "# TadqeeqAI Chat Export",
        f"**Date:** {format_dual_date(lang='en', mode=date_format, with_time=True)}",
        "",
        "---",
        "",
    ]
    for msg in messages:
        role = "User" if msg.get("role") == "user" else "TadqeeqAI"
        lines.extend([f"## {role}", "", msg.get("content", ""), ""])
        if msg.get("sources"):
            lines.append("**Sources:**")
            for src in msg["sources"]:
                lines.append(f"- {src.get('article', '')} ({src.get('document', '')})")
            lines.append("")
        lines.extend(["---", ""])
    lines.extend(["", "*Generated by TadqeeqAI*"])
    return "\n".join(lines)


def export_brief_markdown(brief_text: str, date_format: str = "dual") -> str:
    """Render an executive brief as Markdown with a Generated header."""
    if not brief_text:
        return "# Executive Brief\n\n_(no brief available)_\n"
    header = (
        "# Executive Brief\n"
        f"**Generated:** {format_dual_date(lang='en', mode=date_format, with_time=True)}\n\n"
        "---\n\n"
    )
    return header + brief_text


_COMPLIANCE_CHROME = {
    "en": {
        "title": "Compliance Scan",
        "score_label": "Compliant",
        "pass": "PASS",
        "warn": "WARN",
        "doc_label": "Document",
        "gen_label": "Generated",
        "score_word": "Score",
        "reg_label": "Regulation",
        "footer": "Generated by TadqeeqAI",
    },
    "ar": {
        "title": "تدقيق الامتثال",
        "score_label": "متوافق",
        "pass": "ناجح",
        "warn": "تحذير",
        "doc_label": "الوثيقة",
        "gen_label": "تاريخ التدقيق",
        "score_word": "النتيجة",
        "reg_label": "القاعدة",
        "footer": "تم الإنشاء بواسطة TadqeeqAI",
    },
}


def resolve_compliance_lang(result: dict, requested: str | None) -> str:
    """Pick the language to render a compliance result in.

    'en' / 'ar' override; 'auto' (or anything else) follows the
    document's detected language. Defaults to 'en' if everything's
    unknown.
    """
    if requested in ("en", "ar"):
        return requested
    doc_lang = result.get("doc_language", "en")
    return doc_lang if doc_lang in ("en", "ar") else "en"


def _compliance_check_strings(check: dict, lang: str) -> dict:
    """Pull localized strings out of a check, falling back to flat fields."""
    loc = (check.get("localized") or {}).get(lang) or {}
    return {
        "name": loc.get("name") or check.get("name", ""),
        "regulation": loc.get("regulation") or check.get("regulation", ""),
        "description": loc.get("description") or check.get("description", ""),
        "detail": loc.get("detail") or check.get("detail", ""),
    }


def export_compliance_markdown(
    result: dict,
    date_format: str = "dual",
    lang: str = "auto",
) -> str:
    """Render a compliance result as Markdown."""
    if not result:
        return "# Compliance Scan\n\n_(no result)_\n"
    chrome_lang = resolve_compliance_lang(result, lang)
    chrome = _COMPLIANCE_CHROME[chrome_lang]
    lines = [
        f"# {chrome['title']}",
        f"**{chrome['doc_label']}:** {result.get('filename', '')}",
        f"**{chrome['gen_label']}:** "
        f"{format_dual_date(lang=chrome_lang, mode=date_format, with_time=True)}",
        f"**{chrome['score_word']}:** {result.get('score', 0)}% ({chrome['score_label']})",
        "",
        "---",
        "",
    ]
    for check in result.get("checks", []):
        is_pass = check.get("status") == "compliant"
        status_label = chrome["pass" if is_pass else "warn"]
        icon = "✓" if is_pass else "⚠"
        strings = _compliance_check_strings(check, chrome_lang)
        lines.extend([
            f"## {icon} {strings['name']} ({status_label})",
            "",
            f"**{chrome['reg_label']}:** {strings['regulation']}",
            "",
            strings["detail"],
            "",
            "---",
            "",
        ])
    lines.append(f"*{chrome['footer']}*")
    return "\n".join(lines)


def export_library_markdown(
    messages: list[dict],
    category_label: str = "",
    clause_title: str = "",
    date_format: str = "dual",
) -> str:
    """Render a library-mode conversation as Markdown with Topic/Category header."""
    if not messages:
        return "# TadqeeqAI · Clause Library Discussion\n\n_(empty discussion)_\n"
    header_label = clause_title or category_label or "Clause Library"
    lines = [
        "# TadqeeqAI · Clause Library Discussion",
        "",
        f"**Topic:** {header_label}",
    ]
    if category_label and clause_title:
        lines.append(f"**Category:** {category_label}")
    lines.append(f"**Generated:** {format_dual_date(lang='en', mode=date_format, with_time=True)}")
    lines.extend(["", "---", ""])
    for msg in messages:
        label = "Question" if msg.get("role") == "user" else "Response"
        lines.extend([f"## {label}", "", msg.get("content", ""), ""])
        if msg.get("sources"):
            lines.append("**Sources:**")
            for src in msg["sources"]:
                line = f"- {src.get('article', '')}"
                if src.get("title"):
                    line += f": {src['title']}"
                lines.append(line)
            lines.append("")
        lines.extend(["---", ""])
    lines.extend(["", "*Generated by TadqeeqAI · Clause Library*"])
    return "\n".join(lines)
